import { app, Tray, Menu, nativeImage, shell, clipboard, dialog, BrowserWindow, MenuItemConstructorOptions } from 'electron';
import path from 'node:path';
import fs from 'node:fs';
import { checkLatestRelease } from './updater';

export interface TrayDeps {
  getMainWindow: () => BrowserWindow | null;
  showOrCreateMainWindow: () => Promise<void> | void;
  getDefaultOutDir: () => string | null;
  log: (msg: string) => void;
}

let trayInstance: Tray | null = null;

const HTTP_PROBE = /^https?:\/\/\S+$/i;

function pickTrayIconPath(): string | null {
  // macOS menu-bar icons must be "template images": a single-colour
  // mask (black + alpha) that AppKit re-tints based on the menu bar
  // appearance (light/dark). Feeding our full-colour brand logo into
  // setTemplateImage() collapses every non-transparent pixel into one
  // tone — typically a solid white blob on a light menu bar — which
  // is exactly the bug the user reported. We ship a dedicated
  // single-colour mask at build/icons/trayTemplate.png (generated by
  // scripts/build-tray-template.mjs from the brand logo's alpha) so
  // macOS gets a proper template image, and falls back to the colour
  // logo for Windows / Linux where template-image semantics don't
  // apply.
  const candidates = process.platform === 'darwin'
    ? ['build/icons/trayTemplate.png']
    : ['build/icons/32x32.png', 'build/icons/64x64.png', 'build/icon.png'];
  for (const rel of candidates) {
    const abs = path.resolve(app.getAppPath(), rel);
    if (fs.existsSync(abs)) return abs;
    const cwdAbs = path.resolve(process.cwd(), rel);
    if (fs.existsSync(cwdAbs)) return cwdAbs;
  }
  return null;
}

function buildTrayImage(): Electron.NativeImage {
  const p = pickTrayIconPath();
  if (!p) return nativeImage.createEmpty();
  // R-86 #tray-retina — 不要 resize() 后再 setTemplateImage()。
  // createFromPath 会自动找同目录 `*@2x.png` 作为 Retina representation，
  // 让 menu bar 在 1× / 2× 屏分别渲染清晰；resize 会摊平 representations，
  // Retina menu bar 收到一张 18×18 单图后被拉成 36 像素，结果就是看不清/
  // 显示成"空槽"。直接交给 Electron 管理；setTemplateImage 触发 AppKit
  // light/dark 自适应 tint。
  const img = nativeImage.createFromPath(p);
  if (process.platform === 'darwin') {
    img.setTemplateImage(true);
    return img;
  }
  return img.resize({ width: 16, height: 16 });
}

export function isUrlLikeClipboard(): { ok: true; url: string } | { ok: false } {
  const raw = clipboard.readText('clipboard') || '';
  const trimmed = raw.trim();
  if (!trimmed || trimmed.length > 4096) return { ok: false };
  if (!HTTP_PROBE.test(trimmed)) return { ok: false };
  return { ok: true, url: trimmed };
}

export async function sniffClipboardURL(deps: TrayDeps): Promise<void> {
  const result = isUrlLikeClipboard();
  await deps.showOrCreateMainWindow();
  const win = deps.getMainWindow();
  if (!win || win.isDestroyed()) {
    deps.log('tray.sniffClipboard: no main window after show');
    return;
  }
  const wc = win.webContents;
  if (!result.ok) {
    wc.send('tray:toast', { level: 'warn', message: '剪贴板没有可识别的 URL(需以 http/https 开头)' });
    return;
  }
  wc.send('tray:sniff-url', { url: result.url });
  deps.log(`tray.sniffClipboard: dispatched url=${result.url.slice(0, 80)}`);
}

export async function openOutputDir(deps: TrayDeps): Promise<void> {
  const dir = deps.getDefaultOutDir();
  if (!dir) {
    deps.log('tray.openOutputDir: defaultOutDir unavailable');
    const win = deps.getMainWindow();
    if (win && !win.isDestroyed()) {
      win.webContents.send('tray:toast', { level: 'warn', message: '尚未确定输出目录,请先在 App 内运行一次任务' });
    }
    return;
  }
  try {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const errMsg = await shell.openPath(dir);
    if (errMsg) deps.log(`tray.openOutputDir: shell.openPath returned ${errMsg}`);
  } catch (e) {
    deps.log(`tray.openOutputDir failed: ${(e as Error).message}`);
  }
}

function buildContextMenu(deps: TrayDeps): Menu {
  const items: MenuItemConstructorOptions[] = [
    {
      label: '显示主窗',
      click: () => { void deps.showOrCreateMainWindow(); },
    },
    {
      label: '从剪贴板嗅探 URL',
      click: () => { void sniffClipboardURL(deps); },
    },
    {
      label: '打开输出目录',
      click: () => { void openOutputDir(deps); },
    },
    { type: 'separator' },
    {
      label: '上次任务回看',
      click: () => {
        void deps.showOrCreateMainWindow();
        const win = deps.getMainWindow();
        if (win && !win.isDestroyed()) {
          deps.log('tray menu click: 上次任务回看 -> tray:navigate { tab: history }');
          win.webContents.send('tray:navigate', { tab: 'history' });
        } else {
          deps.log('tray menu click: 上次任务回看 -> mainWindow gone, IPC dropped');
        }
      },
    },
    {
      label: '一键重传最近产物',
      click: () => {
        void deps.showOrCreateMainWindow();
        const win = deps.getMainWindow();
        if (win && !win.isDestroyed()) {
          deps.log('tray menu click: 一键重传最近产物 -> tray:reupload-latest');
          win.webContents.send('tray:reupload-latest');
        } else {
          deps.log('tray menu click: 一键重传最近产物 -> mainWindow gone, IPC dropped');
        }
      },
    },
    { type: 'separator' },
    {
      label: `关于 Gif Toolkit ${app.getVersion()}`,
      click: () => { app.showAboutPanel(); },
    },
    {
      // R-UPDATE — Tray-menu update check. Self-contained: hits the
      // same `checkLatestRelease` shared with the IPC + startup probe
      // (so the 6h cache is unified), then surfaces a modal dialog
      // because the tray flow has no webContents to fan out to. The
      // dialog has a "下载最新版" button only when an update actually
      // exists; on the latest version we still show a friendly OK
      // dialog (the user explicitly clicked, they deserve feedback).
      label: '检查更新…',
      click: async () => {
        deps.log('tray menu click: 检查更新');
        try {
          const r = await checkLatestRelease({ force: true });
          if (r.error) {
            await dialog.showMessageBox({
              type: 'warning',
              title: '检查更新失败',
              message: '无法获取最新版本信息',
              detail: `${r.error}\n\n当前版本: v${r.current}\n请确认网络可访问 api.github.com,或稍后再试。`,
              buttons: ['确定'],
              defaultId: 0,
            });
            return;
          }
          if (r.hasUpdate && r.htmlUrl) {
            const choice = await dialog.showMessageBox({
              type: 'info',
              title: '发现新版本',
              message: `Gif Toolkit v${r.latest} 已发布`,
              detail: [
                `当前版本: v${r.current}`,
                `最新版本: v${r.latest}`,
                r.releaseName ? `发布: ${r.releaseName}` : '',
                r.publishedAt ? `时间: ${r.publishedAt}` : '',
              ].filter(Boolean).join('\n'),
              buttons: ['下载最新版', '稍后'],
              defaultId: 0,
              cancelId: 1,
            });
            if (choice.response === 0) {
              shell.openExternal(r.htmlUrl).catch(() => undefined);
            }
          } else {
            await dialog.showMessageBox({
              type: 'info',
              title: '已是最新版',
              message: `当前版本 v${r.current} 已是最新。`,
              detail: r.latest ? `已检查 GitHub Releases（最新 v${r.latest}）。` : '',
              buttons: ['确定'],
              defaultId: 0,
            });
          }
        } catch (e) {
          deps.log(`tray check update failed: ${(e as Error).message}`);
        }
      },
    },
    {
      label: '退出',
      // We use an explicit click + accelerator instead of `role: 'quit'`
      // because on macOS Electron 31's tray-menu rendering of `role: 'quit'`
      // injects a leading icon for the row, which forces the menu's
      // icon column on for the entire menu and visibly mis-indents
      // every other (icon-less) item. Going through app.quit() keeps
      // the standard quit semantics + Cmd+Q accelerator without the
      // decoration, so all rows align flush-left.
      accelerator: process.platform === 'darwin' ? 'Command+Q' : 'Control+Q',
      click: () => { app.quit(); },
    },
  ];
  return Menu.buildFromTemplate(items);
}

export function setupTray(deps: TrayDeps): Tray | null {
  if (trayInstance) return trayInstance;
  try {
    const image = buildTrayImage();
    const tray = new Tray(image);
    tray.setToolTip('Gif Toolkit');
    const refreshMenu = (): void => { tray.setContextMenu(buildContextMenu(deps)); };
    refreshMenu();
    if (process.platform !== 'darwin') {
      tray.on('click', () => { void deps.showOrCreateMainWindow(); });
    }
    tray.on('right-click', () => { refreshMenu(); tray.popUpContextMenu(); });
    trayInstance = tray;
    deps.log('tray: ready');
    return tray;
  } catch (e) {
    deps.log(`tray: setup failed: ${(e as Error).message}`);
    return null;
  }
}

export function destroyTray(): void {
  if (trayInstance && !trayInstance.isDestroyed()) {
    try { trayInstance.destroy(); } catch { /* best-effort */ }
  }
  trayInstance = null;
}
