/**
 * Session-scoped operation log types.
 *
 * Background: every "嗅探 → 选择 → 处理 → 上传" round needs a single
 * append-only log so the user can replay why a particular GIF
 * appeared / didn't appear / was duplicated. The buffer is keyed by
 * a `sessionId` minted when a sniff begins, and follows the result
 * through processor and (optionally) uploader. The same id is
 * persisted on the corresponding [HistoryRecord](./../../renderer/components/useHistory.ts)
 * so the history detail panel can render the log inline and export
 * it.
 *
 * Pure type-only file — no runtime side effects, safe to import from
 * both renderer and main. Lives under `shared/types` so the preload
 * bridge re-exports it for free.
 */

/**
 * Severity of a log entry. Mirrors the conventional debug/info/warn/
 * error matrix; renderer can colour-code on this.
 */
export type SessionLogLevel = 'debug' | 'info' | 'warn' | 'error';

/**
 * High-level pipeline stage the entry was emitted from. Free-form
 * `substep` (per-entry) carries finer granularity (e.g. 'http.fetch'
 * inside `sniff`).
 */
export type SessionLogStage =
  | 'session'   // session-level meta: open / close / cancel
  | 'sniff'     // every sniff backend (url / webview / system-chrome / ytdlp / offline)
  | 'process'   // processor.ts / ffmpeg / compressLoop
  | 'upload'    // uploader backends
  | 'resolve'   // embed resolver (yt-dlp)
  | 'toolbox';  // R-TB-LOG-V1 — toolbox chain runner: start / per-step / cancel / size-regression

/**
 * One immutable entry. Always carries the wall-clock timestamp the
 * main process saw the event at, so a later replay reads the same
 * order across timezones / clock skew.
 */
export interface SessionLogEntry {
  /** Owning session id. Generated by [openSession](../../main/sessionLogger.ts). */
  sessionId: string;
  /** Strictly increasing per-session sequence number. The DB also
   *  carries this so a re-sort by `seq` survives identical timestamps
   *  across tight bursts. */
  seq: number;
  /** Wall-clock ms when the entry was recorded (Date.now()). */
  ts: number;
  level: SessionLogLevel;
  stage: SessionLogStage;
  /** Free-form sub-step tag (e.g. `http.fetch`, `compress.phaseB`,
   *  `dedup.replace`). Caller-defined; only used for filtering and
   *  rendering, never branched on. */
  substep?: string;
  /** Human-readable message line. Pasted verbatim into .log export. */
  message: string;
  /**
   * Optional structured payload. Serialised as JSON in the DB. Use
   * for things like the SniffedMedia url that was deduped, the
   * compress phase byte-target, the upload backend label, etc. The
   * renderer renders this as a collapsible code block.
   *
   * Keep payloads small (a few hundred bytes); large blobs
   * (binary) MUST be summarised to a hash + size.
   */
  data?: Record<string, unknown>;
}

/**
 * Snapshot of an entire session, returned by `db:sessionLogs:read`
 * and used by the renderer detail panel + export pipeline.
 */
export interface SessionLogSnapshot {
  sessionId: string;
  /** Wall-clock when openSession was called. */
  openedAt: number;
  /** Wall-clock when the session was closed (success / cancel /
   *  error). `undefined` while still in flight. */
  closedAt?: number;
  /** The page URL that initiated the sniff. Empty string when the
   *  session was opened by an offline-import or toolbox path that
   *  doesn't know a URL up-front. */
  pageUrl: string;
  /** Page title captured at sniff time, if any. */
  title?: string;
  /** sniff / webview / system-chrome / ytdlp-direct / offline-import
   *  / toolbox / process-only — used purely for display. */
  origin?: string;
  /** Final outcome label: `done` / `cancelled` / `error`; `undefined`
   *  while still in flight. */
  outcome?: 'done' | 'cancelled' | 'error';
  entries: SessionLogEntry[];
}

/** Format choices when exporting a session log to disk. */
export type SessionLogExportFormat = 'log' | 'json';
